FROM golang:alpine
RUN apk add make

ARG GIT_COMMIT

WORKDIR /go/src/
COPY . /go/src/

# Erase executables that were copied from the COPY cmd above
RUN find . -maxdepth 1 -type f -executable -exec rm {} \;

# Force static builds
ENV GO_EXTLINK_ENABLED=0
ENV CGO_ENABLED=0
# -w removes debugging info
ENV BUILDFLAGS -ldflags \
	\"-w -extldflags -static \
      -X=github.com/xregistry/server/common.GitCommit=$GIT_COMMIT \" \
	-tags netgo -installsuffix netgo

RUN make xr

FROM alpine

LABEL org.opencontainers.image.source https://github.com/xregistry/server

COPY --from=0 /etc/ssl/certs/ca-certificates.crt \
	/etc/ssl/certs/ca-certificates.crt

COPY --from=0 /go/src/xr /xr

ENTRYPOINT [ "/xr" ]
