#!/bin/bash

TMP=/tmp/output$RANDOM
trap 'rm -f $TMP' EXIT

if [[ "$1" == "-"* ]]; then
    echo "${1:1}"
    shift
else
    echo "$@"
fi

echo -e '$' "$@\n" > $TMP 2>&1

if ! "$@" >> $TMP 2>&1; then
    echo
	cat $TMP
	exit 1
fi
