#!/bin/bash

TMP=/tmp/output$RANDOM
trap 'rm -f $TMP' EXIT

if [[ "$1" == "-"* ]]; then
    # If what we want to show is different from the actual command then make
    # the first args the command to show prefixed with a "-"
    echo "${1:1}"   # remove the "-" and echo it
    shift           # skip over this arg
elif [[ "$1" == "@"* ]]; then
    # Don't echo any cmd if it starts with "@"
    args=("$@")
    set -- "${1:1}" "${args[@]:1}"
else
    # echo the command as is
    echo "$@"
fi

echo -e '$' "$@\n" > $TMP 2>&1

if ! "$@" >> $TMP 2>&1; then
    echo
	cat $TMP
	exit 1
fi
