#!/bin/bash

#              Load    GETs   QUERY
# ee74f5538113 12m27s  46m5s  55s     old,w/views
# old :        12m     46m (w/views)
# new1:        21m     2m58s
# new2:        14m     2m48s
# ecec1a45f506 14m30s  2m
# 93415365de07 14m22s  2m47s  0m43s
# new3:        21m     2m45s          remove last inline Valdate calls
# new4:        12m     2m52s          removed recursive validate calls
# new4:        12m     2m46s  43s
# 8284d7b2ce7b 12m0s   2m46s  43s     rm more validate calls
# 9c17ac6381c9 11m58s  2m47s  43s     tons of xref fixes/optimizations
# f58db84dbc20 11m15s  2m49s  43s     old sql table names, moved funcs/tests
# cfe72b3bb9a2 11m38s  2m46s  43s     partial move of test to use http
# f6df0bef5d8f 11m14s  2m54s  43s     fix hasDoc model updates
# c4be9c4f3fdc 11m21s  2m51s  43s     ValidateRes cleanup/group constraints
# f819d7594a64 2m20s   2m50s  44s     phase 3 of tx fixes
# 43c279ee4284 2m22s   2m46s  44s
# 7a2f960cb6c0 2m21s   2m49s  43s     Remove readonly/immutable attrs
# 4831457b2740 2m15s   2m45s  34s
# 11adb65394fd 2m13s   2m43s  34s     New logging and TXs in errors

set -e

echo
echo "# Running the benchmark"
 
XR_SERVER=http://localhost:8080/xregs/Large
CMD="curl -s "
SEARCH="Done loading"
# SEARCH="Listening" ; CMD="echo $CMD"

pkill xrserver || echo -n
./xrserver --verify
(XR_LOAD_LARGE=1 ./xrserver --recreatedb --samples -v 2>&1 ) | tee server.out &
trap "pkill xrserver ; rm -f server.out" EXIT

sleep 5 # just to avoid an error on grep because server.out isn't there yet
while ! grep "$SEARCH" server.out > /dev/null ; do 
  sleep 10
done

TIMEFORMAT="GETs: %0lR" ; time (
for d in `seq 0 9` ; do
  $CMD $XR_SERVER/dirs/dir$d > /dev/null
  for f in `seq 0 149` ; do
    $CMD $XR_SERVER/dirs/dir$d/files/file$f$details?inline > /dev/null
    for v in `seq 0 4` ; do
      $CMD $XR_SERVER/dirs/dir$d/files/file$f/versions/v$v\$details > /dev/null
    done
  done
  echo "Done GETting /dirs/dir$d"
done
)

query="$CMD $XR_SERVER/?filter=dirs.files.versions.epoch,dirs.files.fileid&filter=dirs.files.versions.versionid"

TIMEFORMAT=" / QUERY: %0lR"; time echo -n $($query | grep dirscount)

# grep "$SEARCH" server.out
