#!/bin/bash

# old : load: 12m   get: 46m (w/views)
# new1: load: 21m   get:  2m58s
# new2: load: 14m   get:  2m48s

set -e
 
export XR_SERVER=http://localhost:8080/reg-Large

touch server.out
(XR_LOAD_LARGE=1 ./xrserver --recreatedb --samples -v 2>&1 ) | tee server.out &

cmd="curl -s "
search="Done loading"
# search="Listening" ; cmd="echo $cmd"

while ! grep "$search" server.out > /dev/null ; do 
  sleep 10
done

time (
for d in `seq 0 9` ; do
  $cmd $XR_SERVER/dirs/dir$d > /dev/null
  for f in `seq 0 149` ; do
    $cmd $XR_SERVER/dirs/dir$d/files/file$f$details?inline > /dev/null
    for v in `seq 0 4` ; do
      $cmd $XR_SERVER/dirs/dir$d/files/file$f/versions/v$v\$details > /dev/null
    done
  done
  echo "Done with /dirs/dir$d"
done
)

grep "$search" server.out
rm -f server.out
pkill xrserver
