#!/bin/bash

# make sure "xr" CLI is in your PATH
# You can build it with: "make xr"

XREG_REPO=https://raw.githubusercontent.com/xregistry/spec/refs/heads/main

# Start a new xRegistry server
docker run --name xreg -dti -p 8080:8080 ghcr.io/xregistry/xreg-server-all

# Wait for the server to be ready before we continue
while ! xr get > /dev/null 2>&1 ; do sleep 1 ; done

# Define a sample doc-store model using the sample from the xReg spec repo
xr model update -d @$XREG_REPO/core/samples/doc-store-model.json

# Now upload some files into it

# Point to our locally running xReg server
XR_SERVER=localhost:8080

xr create dirs/mydocs/files/todo-list -d "All caught up!"

echo "
Team members:
- Jon
- Lola
- Sam
- Mary
- Casey
" | xr create dirs/workdocs/files/team -d @-

# Then go to: http://localhost:8080?ui to explore
# Use: docker rm -f xreg
# to stop and delete the server
