#!/bin/bash

# make sure "xr" CLI is in your PATH
# You can build it with: "make xr", or download it from:
# https://github.com/xregistry/server/releases/tag/dev

# Start a new xRegistry server, if you don't have one already running
docker run --name xreg -dti -p 8080:8080 ghcr.io/xregistry/xreg-server-all

# Point to this server
XR_SERVER=localhost:8080

# Wait for the server to be ready before we continue
while ! xr get > /dev/null 2>&1 ; do sleep 1 ; done

# Define the model we want to use, in this case the "CloudEvents" model,
# defined by the xRegistry team, which contains 3 different sub-models under
# it (endpoints, messages, schemas)
xr model update -d @https://raw.githubusercontent.com/xregistry/spec/refs/heads/main/cloudevents/model.json

xr import -d @https://raw.githubusercontent.com/xregistry/spec/refs/heads/main/cloudevents/samples/scenarios/contoso-erp-jsons07.xreg.json

# Then go to: http://localhost:8080?ui to explore
# Or stop and delete the server: docker rm -f xreg
