name: CI
on:
  push:
    branches:
      - master

jobs:
  build_test_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set DOCKERHUB env var to use the github org name
        run: echo "DOCKERHUB=ghcr.io/${GITHUB_REPOSITORY%/*}/" >> $GITHUB_ENV

      - name: Show env vars for debugging
        run: env | sort

      - name: ghcr.io login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build, test, push
        run: make mysql test push

      - name: build cmds for all platforms
        run: make cmds-all

      - name: push all cmds to the 'dev' release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            xr.*
            xrserver.*
          artifactErrorsFailBuild: true
          allowUpdates: true
          body: "Latest development build of the 'xr(server)' executables"
          commit: master
          draft: true
          tag: dev
          omitBodyDuringUpdate: true
          prerelease: true
          removeArtifacts: true
          replacesArtifacts: true

      - env:
          SOAPHUB_SSH_KEY: ${{ secrets.SOAPHUB_SSH_KEY }}
        # Setup each host such that the SSH KEY can only run one command.
        # In .ssh/authorized_keys prefix it with: command="..."
        # e.g. command="/../restart" ssh-sra AAA...
        run: misc/restart SOAPHUB_SSH_KEY ubuntu@soaphub.org

