name: PR-CI
on:
  pull_request

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Show env vars for debugging
        run: env | sort

      - name: build, test
        run: make mysql test

      - name: benchmark
        run: make benchmark | grep "[0-9]m[0-9][0-9]s" | sed "s/^/::/"

