name: Regen hub.xreg.io site
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  trigger-other-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Send event to hub.xreg.io repo
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.XREGIO_PAT }}" \
          https://api.github.com/repos/xregistry/hub.xregistry.io/dispatches \
          -d '{"event_type": "server_updated"}'
